name: CommandBlock-Support
main: cbs.plugin.EmulationManager
version: "1.20a"
authors: ["ME1312"]
website: "https://github.com/ME1312/CommandBlock-Support"
#commands:
#  cbs:
#    description: "CommandBlock Support"
#    usage: "/cbs [-flags] [command] [args...]"